# Set the theme for your site (optional)
remote_theme: pages-themes/cayman@v0.2.0

# Define the base URL (optional)
baseurl: ""

# Site title and description
title: "Derry Yeh"
description: ""

# Enable Jekyll's built-in plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed

collections:
  posts:
    output: true
    permalink: /:collection/:name
